name: Deploy Telegram Bot (Infra + Lambda Code)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      S3_BUCKET: mirrowchanbot-bucket-bucket
      LAMBDA_ZIP_KEY: telegram_bot/lambda.zip
      TERRAFORM_DIR: infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Apply (Infrastructure & SSM Setup)
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -auto-approve

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Build Lambda ZIP package
        run: |
          pip install -r lambda/requirements.txt --target lambda/package/
          cd lambda/package && zip -r9 ../../lambda.zip .
          cd ../ && zip -g lambda.zip bot_handler.py

      - name: Upload Lambda ZIP to S3
        run: |
          aws s3 cp lambda.zip s3://${{ env.S3_BUCKET }}/${{ env.LAMBDA_ZIP_KEY }}

      - name: Terraform Apply (Lambda Code Update)
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -auto-approve
